### 친구 요청 보내기
# @no-cookie-jar
POST http://localhost:8080/api/friends/request/1
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 친구 요청 취소
# @no-cookie-jar
DELETE http://localhost:8080/api/friends/request/2
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 친구 요청 수락
# @no-cookie-jar
POST http://localhost:8080/api/friends/status/2/accept
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 친구 요청 거절
# @no-cookie-jar
POST http://localhost:8080/api/friends/status/2/reject
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 친구 목록 조회 (ACCEPTED 상태)
# @no-cookie-jar
GET http://localhost:8080/api/friends/friend/accept
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 친구 대기 목록 조회 (WAITING 상태)
# @no-cookie-jar
GET http://localhost:8080/api/friends/friend/waiting
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 친구 삭제
# @no-cookie-jar
DELETE http://localhost:8080/api/friends/friend/1
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 자기 자신에게 친구 요청 (SelfRequestException)
POST http://localhost:8080/api/friends/request/3
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 중복 친구 요청 (DuplicateFriendRequestException)
POST http://localhost:8080/api/friends/request/1
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 존재하지 않는 친구 요청 수락 (FriendRequestNotFoundException)
POST http://localhost:8080/api/friends/status/999/accept
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 존재하지 않는 친구 요청 거절 (FriendRequestNotFoundException)
POST http://localhost:8080/api/friends/status/999/reject
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

###

### 존재하지 않는 친구 삭제 (FriendNotFoundException)
DELETE http://localhost:8080/api/friends/friend/999
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}
